#!/usr/bin/env bash


# required and default variables
ERR=0
FIND_PATH=1

REQ_PYVER='2.7'
DEF_PYENV="${HOME}/.pyenv"
DEF_PYBREW="${HOME}/.pythonbrew"
PYBRAT_HOME="${HOME}/.pybrat"

# split $PATH
IFS=:

DIRS=
read DIRS <<END
$PATH
END



# Error logging
function _err {
    let ERR=ERR+1
}



# Function to check $PATH for given path
function _search_path {
    for dir in $DIRS; do
        if [[ "$dir" == "$1" ]]; then 
            [ -e "$dir" ] && let FIND_PATH=1 || let FIND_PATH=0
        fi
    done
}



function _config_shrc_pybrew {

    echo; read -p "Configure 'pythonbrew' in your '~/.bashrc'? [y/N]: "
    if [[ "$REPLY" != "y" ]]; then
	printf "\n==> ERROR: 'pythonbrew' needs to be configured to work!\n"
	_err; return
    fi

    printf "\n# 'pythonbrew' environment configuration\n" >> ${HOME}/.bashrc
    echo "[[ -s ${HOME}/.pythonbrew/etc/bashrc ]] && source ${HOME}/.pythonbrew/etc/bashrc" \
	>> ${HOME}/.bashrc

    echo; echo '==> DONE! You need to restart your shell. Type `exec $SHELL`.'
    printf "\n(On uninstall, delete 'pythonbrew' section from '${HOME}/.bashrc'.)\n"

    return
}



# Check if 'pythonbrew' installed and if not, install.
function _check_req_pybrew {

    _search_path "${DEF_PYBREW}/bin"
    [ ! $FIND_PATH ] && return

    if [ -e "$DEF_PYBREW" ]; then
	echo "==> WARNING: 'pythonbrew' installed but not configured."
	echo "Did you configure your shell script and type `exec $SHELL`?"
        _config_shrc_pybrew
	_err; return
    fi

    # good to install ...
    echo "==> ERROR: This (development) version still requires (deprecated) 'pythonbrew'."
    read -p "Use 'curl' to install 'pythonbrew' to defaults? [y/N]: "
    [[ "$REPLY" != "y" ]] && _err && return

    # ... so curl it all to defaults
    echo
    curl -kL http://xrl.us/pythonbrewinstall | bash
    if [ ! -e "${DEF_PYBREW}" ]; then
	echo "==> ERROR: 'pythonbrew' did not install correctly."
	_err; return
    fi

    _config_shrc_pybrew
    _err; return
}



# Configure the user's shell script if they want.
function _config_shrc_pyenv {

    echo; read -p "Configure 'pyenv' for your shell? [y/N]: "
    if [[ "$REPLY" != "y" ]]; then
        printf "\n==> ERROR: 'pyenv' needs to be configured to work!\n"
        echo "Read the 'README.md' located in the '${DEF_PYENV}' directory."
	_err; return
    fi

    local sh=
    echo; read -p "Using: [0] .bashrc, OR [1] .bash_profile ? "
    case $REPLY in
        0)
            sh=".bashrc"
            ;;
        1)
            sh=".bash_profile"
            ;;
        *)
	    _err; return
            ;;
    esac

    # append pretty 'pyenv' env vars to the chosen shell cfg
    printf "\n# 'pyenv' environment configuration\n" >> ${HOME}/${sh}
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ${HOME}/${sh}
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ${HOME}/${sh}
    echo 'eval "$(pyenv init -)"' >> ${HOME}/${sh}
    
    echo; echo '==> DONE! You need to restart your shell. Type `exec $SHELL`.'
    printf "\n(On uninstall, delete 'pyenv' section from '${HOME}/${sh}'.)\n"

    return
}



# Check if 'pyenv' and plugins are installed and if not, install.
function _check_req_pyenv {

    _search_path "${DEF_PYENV}/bin"
    [ ! $FIND_PATH ] && return

    # check for .pyenv directory in case installed but not config'd
    if [ -e "$DEF_PYENV" ]; then
        echo "==> ERROR: 'pyenv' installed but not configured."
        echo "Did you read the 'README.md' in '${DEF_PYENV}'?"
        _config_shrc_pyenv
	_err; return
    fi

    # good to install here ...
    echo "==> ERROR: This version of PyBrat requires 'pyenv'."
    read -p "Use 'git' to clone and install 'pyenv' to defaults? [y/N]: "
    [[ "$REPLY" != "y" ]] && _err && return
    
    # ... so clone it all from github
    echo
    git clone git://github.com/yyuu/pyenv.git $DEF_PYENV
    if [ ! -e "$DEF_PYENV" ]; then
        echo "==> ERROR: 'pyenv' did not install correctly."
	_err; return
    fi
    echo
    git clone git://github.com/yyuu/pyenv-virtualenv.git ${DEF_PYENV}/plugins/pyenv-virtualenv
    if [ ! -e "${DEF_PYENV}/plugins/pyenv-virtualenv" ]; then
        echo "==> ERROR: 'pyenv-virtualenv' did not install correctly."
	_err; return
    fi

    _config_shrc_pyenv
    _err; return
}



# bootstrap python2 if necessary
function _check_req_pyver {

    local pyver=`which python${REQ_PYVER}`

    [[ "$pyver" == *"$reqver"* ]] && return

    echo "This version of PyBrat requires Python ${REQ_PYVER}."
    read -p "Bootstrap Python-${REQ_PYVER} with 'pyenv'? [y/N]: "
    [[ "$choice" != "y" ]] && _err && return

#        _install_req_pyver
}



function _check_req {
    _check_req_pyenv
    _check_req_pyver
    _check_req_pybrew     # to be deprecated
}


# make sure the python installer exists first, then run it
function _run_pyinstall {
    if [ -e "${PWD}/scripts/pybrat_install.py" ]; then 
        /usr/bin/python2 "${PWD}/scripts/pybrat_install.py" $@
    else
        echo "Install module not found."
    fi
}



#===========================================#
#                    MAIN                   #
#===========================================#

OPTIND=1

while getopts "hi" opt; do
    case "$opt" in
        h)
            _run_pyinstall -h; exit 1
            ;;
        i)
            _search_path $PYBRAT_HOME
            [ ! $FIND_PATH ] && echo "PyBrat is already installed. Uninstall first." && exit 1
            ;;
    esac
done

# pre-parse the args before sending to python installer
[[ "$#" == "0" ]] && ARG="-i" || ARG="$1"

# clear to check for dependencies before installing
_check_req
[ ! -z "$ERR" ] && echo "==> ERROR (${ERR}): Try reinstalling after fixing stuff." && exit $ERR

# otherwise, send the args on to python installer ...
_run_pyinstall $ARG

exit
