#!/usr/bin/env bash

if [ -f "./scripts/pybrat_install.py" ]; then 
    /usr/bin/python2 "${PWD}/scripts/pybrat_install.py" "$@"
else
    echo "Installation package not found."
fi

if [ ! -f "~/pythonbrew/bin/pythonbrew" ]; then
    echo "Pythonbrew not installed."
fi
